# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            IST & Unbabel Seminars 1
tagline:          'A Jekyll theme'
description:      ''
url:              'https://ist-unbabel-seminars.github.io'
baseurl:          ''

paginate:         5