# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            IST & Unbabel Seminars
tagline:          'A Jekyll theme'
description:      ''
url:              "ist-unbabel-seminars.github.io"
baseurl:          ""

paginate:         5